- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com #global variable
  vars_files:
    - just-vars.yml
  tasks:
    - name: Print a local variable
      vars:
        URL: task.google.com #local variable
      ansible.builtin.debug:
        msg: Local var URL - {{ URL }} #they are uses local variable

    - name: Print a global variable
      ansible.builtin.debug:
        msg: "{{ URL }}" #they are uses global variable

    # Storing var in other variable
    - name: Task output
      ansible.builtin.shell: ls
      register: out
    - name: Output
      ansible.builtin.debug:
        msg: "{{ out }}"

## KEY: val, Line 11 no quotes needed
# KEY: {{ Val }}, then ansible expects it to be in double quotes, Line 15 - quotes needed

# Variable Precedence - If same variable name is declared in multiple, which one will be picked by Ansible.
# 1. command line variable
# 2. Task Variable
# 3. Play level variable from file
# 4. Play level variable
# 5. Role variables
# 6. Inventory Variables
# 7. Role default variable


# Var: Value
# Variable can have a-z, 0-9, _,

# VAR - TYPE
# Three Types
# Plain Variable - num: 10
# List Variable - num: [10,20]
# Map Variable - num: {a:10,b:20}

# Var -Data TYPES
# String
# Number
# Boolean - True, False, Yes, No ( First letter can be CAPITAL or small)