- name: Variables
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com #global variable
  vars_files:
    - just-vars.yml
  tasks:
    - name: Print a local variable
      vars:
        URL: task.google.com #local variable
      ansible.builtin.debug:
        msg: Local var URL - {{ URL }} #they are uses local variable

    - name: Print a global variable
      ansible.builtin.debug:
        msg: "{{ URL }}" #they are uses global variable

## KEY: val, Line 11 no quotes needed
# KEY: {{ Val }}, then ansible expects it to be in double quotes, Line 15 - quotes needed

# Variable Precedence - If same variable name is declared in multiple, which one will be picked by Ansible.
# . Task Variable
# . Play variable
