- name: Loops
  hosts: localhost
  connection: local
  tasks:
    - name: print fruits
      ansible.builtin.debug:
        msg: Fruit Name - {{ iteam }} #item is default value which is provided by ansible
      loop:
        - apple
        - banana
        - orange
    - name: print fruits with quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ iteam.name }}, Quantity - {{ item.quantity }} #item is default value which is provided by ansible
      loop:
        - { name: apple, quantity: 10 }
        - { name: banana, quantity: 110 }
        - { name: orange, quantity: 1110 }


#